[package]
name = "simplebool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
ariadne = "0.1.5"
chumsky = "0.8.0"
derive_more = "0.99.17"
thiserror = "1.0.31"
util = { path = "../util" }
